name: 'Terraform Apply'
on:
  workflow_dispatch:
    inputs:
      plan:
        required: false
        default: 'vhf-1c-1gb'
        type: string
      snapshot_id:
        required: true
        default: ''
        type: string
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      TF_VAR_plan: ${{ github.event.inputs.plan }}
      TF_VAR_snapshot_id: ${{ github.event.inputs.snapshot_id }}
      TF_VAR_api_key: ${{ secrets.VULTR_API_KEY }}
      
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        working-directory: ./infra
        shell: bash
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./infra
        shell: bash
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve && terraform refresh
        working-directory: ./infra
        shell: bash
      - name: Set env
        id: vars
        run: |
          echo "VULTR_IP=$(terraform output -raw vdi_ip)" >> $GITHUB_OUTPUT
          echo "INSTANCE_ID=$(terraform output -raw instance_id)" >> $GITHUB_OUTPUT
        working-directory: ./infra
      - name: Set attach blockstorage
        id: attach
        run: |
          curl https://${{ secrets.CF_WORKER_URL }}/attach_blockstorage \
            -X POST \
            -H "Content-Type: application/json" \
            --data '{
              "instance_id" : "${{ steps.vars.outputs.INSTANCE_ID }}"  
            }'
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "text": "${{ steps.vars.outputs.VULTR_IP }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    