name: 'Terraform Apply'
on:
  workflow_dispatch:
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      TF_VAR_api_key: ${{ secrets.VULTR_API_KEY }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        working-directory: ./infra
        shell: bash
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./infra
        shell: bash
      - name: Terraform Apply
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: ./infra
        shell: bash